version: "3.5"
services:
  selenoid:
    image: "aerokube/selenoid"
    ports:
      - "4444:4444"
    volumes:
      - "/etc/selenoid/:/etc/selenoid/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/selenoid/logs/:/opt/selenoid/logs/"
    command: ["-listen", ":4444", "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-save-all-logs", "-container-network", "backend"]
    networks:
      - backend

networks:
  backend:
    external:
      name: backend


